# my-values.yaml
frontend:
  replicas: 2        # Run 2 copies of the frontend for high availability
  
cartService:
  replicas: 2

# Image configuration (we'll update this in CI)
images:
  tag: "latest"
  repository: "164885464623.dkr.ecr.us-east-1.amazonaws.com/online-boutique"
